app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Route::get('/', function () {
//     return view('index');
// });
Route::controllers([
   'password' => 'Auth\PasswordController',
]);

Route::get('/', 'Auth\AuthController@getLogin');
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register' , 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

//Block for ACL just use ['auth','roles'] 
//Currently roles section not using anymore
$router->group(['middleware' => ['auth']], function() {
    //Users segment
    Route::resource('/user','UserController');
    Route::resource('/users','Admin\UsersController');

    //Roles segment
    Route::resource('/roles','Admin\RolesController');
    Route::get('/role','Admin\RolesController@roleArea');
    Route::post('/roles/assign','Admin\RolesController@assign');

    //ACL segment
    Route::get('/acl', 'Admin\AclController@update_resources');

    //ACL Permission segment
    Route::get('permissions', 'Admin\AclController@list_permissions');
    Route::get('permissions/{role_id}', 'Admin\AclController@list_permissions');
    Route::post('/permissions','Admin\AclController@add_permission');

    //Category segment
    Route::get('/category/trash','Admin\CategoryController@trashItems');
    Route::get('/category/restore/{c_id}','Admin\CategoryController@restoreItems');
    Route::get('/category/delete/{c_id}','Admin\CategoryController@forceDelete');
    Route::resource('/category','Admin\CategoryController');

    //Mockups
    Route::resource('/mockup3d','Admin\Mockup3dController');
    
    //Template segment
    Route::resource('/template','Admin\TemplateController');
    Route::post('gettemplate','Admin\PatternImageController@getTemplateData');
    Route::get('/edit/{id}','EcoverController@getSizes');

    //Pattrens segment
    Route::get('tabdata','Admin\PatternImageController@loadTabdata');
    Route::resource('/pattern','Admin\PatternImageController');
    Route::get('/showsession','Admin\UsersController@showsession');

    //Route::get('/home', ['as' => '/users', 'uses' => 'Admin\UsersController@index']);
});

//Block for notmal auth
$router->group(['middleware' => ['auth']], function() {
    //Canvas User profile and crop segment
    Route::get('jcrop','Admin\UsersController@jcropview');
    Route::post('/users/jcrop','Admin\UsersController@jcroppost');
    
    //Editor segment
    Route::resource('/canvas','Admin\CanvasController');
    Route::resource('/cover','EcoverController');
    Route::get('/editor/{id}','EcoverController@getSizes');
    
    Route::post('/editor/save','EcoverController@saveCanvas');
    Route::post('/editor/clonesave','EcoverController@cloneCanvas');
    Route::get('/design','EcoverController@getCanvasSizes');
    Route::get('/getCanvasAjax','EcoverController@getCanvasAjax');
    Route::get('/getCategoryAjax','EcoverController@getCategoryAjax');
    Route::get('/home', ['as' => '/editor', 'uses' => 'EcoverController@getSizes']);  
    Route::post('/editor/upload_image/{id}','EcoverController@uploadUserMedia');
    Route::post('/editor/get_user_images/{id}','EcoverController@getUserImages');
    
    //Upload Media and Images segment
    Route::post('/media/uploads','MediaController@uploads');
    Route::post('/media','MediaController@index');
    Route::resource('/media','MediaController');
    Route::post('/media','MediaController@index');
    Route::post('/media/{id}','MediaController@destroy');
    
   
});

 //Export Canvas segment
Route::post('/exports','Admin\CanvasController@exportCanvas');
 

resources/views/admin/template/create.blade.php
@extends ('app')
@section('content')

<style>
.page-content-wrapper .page-content {
  padding: 0;
}
</style>

<div>
    <iframe src="<?php echo url(); ?>/editor/1" style="width: 100%;height: 100vh;border:none;"></iframe> 
</div>

@stop

resources/views/admin/template/index.blade.php
@extends ('app')
@section('content')
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active">
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i>List Templates</div>
                <div class="tools">
                    <a href="javascript:;" class="collapse"> </a>
                </div>
            </div>
            <div class="portlet-body flip-scroll">
                <table class="table table-bordered table-striped table-condensed flip-content">
                    <thead class="flip-content">
                        @if($template && count($template) >= 1)
                        <tr>
                            <th></th>
                            <th>Template Title</th>
                            <th>User Name</th>
                            <th>Price</th>
                            <th>Dimension</th>
                            <th>Created Date</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($template as $item)
                        <tr>
                            <td>
                                <a href="{!! $item->img_data !!}" target="_blank">
                                    <img src="{!! $item->img_data !!}" style="width: 50px;height:50px;">
                                </a>
                            </td>
                            <td>{!! $item->title !!}</td>
                            <td>{!! $item->users['first_name'] !!} {!!$item->users['last_name']!!}</td>
                            <td>{!! $item->price !!}</td>
                            <td>{!! $item->width !!}*{!! $item->height !!}</td>
                            <td>{!! $item->created_at->format('d-M, Y  (H:i:s)') !!}</td>
                            <td> 
                                <!--<a href="{!!route('template.edit', $item->id)!!}" class="btn btn-outline btn-circle btn-sm purple">Edit Information</a>-->
                                {!! Form::open(['method' => 'DELETE', 'class'=>'del-css', 'route' => array('template.destroy', $item->id),'onsubmit' => 'return ConfirmDelete()']) !!}
                                <button type="submit" class="submit-btn-cls"> 
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </button>
                                {!! Form::close() !!} 
                            </td>
                        </tr>

                        @endforeach
                        @else
                    <h3 align='center'>Nothing found!</h3>
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div>
    <a class="btn btn-success" href="<?php echo url(); ?>/template/create" style="margin-bottom:15px;">Create New</a>
</div>

<div class="pull-left">
    {!! $template->total() !!} template(s) total
</div>

<div class="pull-right">
    {!! $template->render() !!}
</div>
<div class="clearfix"></div>
<script>
    function ConfirmDelete()
    {
        var x = confirm("Are you sure you want to delete this Template ?. This will not be recoverable press OK to continue.");
        if (x)
            return true;
        else
            return false;
    }
</script>
@stop