app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Route::get('/', function () {
//     return view('index');
// });
Route::controllers([
   'password' => 'Auth\PasswordController',
]);

Route::get('/', 'Auth\AuthController@getLogin');
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register' , 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

//Block for ACL just use ['auth','roles'] 
//Currently roles section not using anymore
$router->group(['middleware' => ['auth']], function() {
    //Users segment
    Route::resource('/user','UserController');
    Route::resource('/users','Admin\UsersController');

    //Roles segment
    Route::resource('/roles','Admin\RolesController');
    Route::get('/role','Admin\RolesController@roleArea');
    Route::post('/roles/assign','Admin\RolesController@assign');

    //ACL segment
    Route::get('/acl', 'Admin\AclController@update_resources');

    //ACL Permission segment
    Route::get('permissions', 'Admin\AclController@list_permissions');
    Route::get('permissions/{role_id}', 'Admin\AclController@list_permissions');
    Route::post('/permissions','Admin\AclController@add_permission');

    //Category segment
    Route::get('/category/trash','Admin\CategoryController@trashItems');
    Route::get('/category/restore/{c_id}','Admin\CategoryController@restoreItems');
    Route::get('/category/delete/{c_id}','Admin\CategoryController@forceDelete');
    Route::resource('/category','Admin\CategoryController');

    //Mockups
    Route::resource('/mockup3d','Admin\Mockup3dController');
    
    //Template segment
    Route::resource('/template','Admin\TemplateController');
    Route::post('gettemplate','Admin\PatternImageController@getTemplateData');
    Route::get('/edit/{id}','EcoverController@getSizes');

    //Pattrens segment
    Route::get('tabdata','Admin\PatternImageController@loadTabdata');
    Route::resource('/pattern','Admin\PatternImageController');
    Route::get('/showsession','Admin\UsersController@showsession');

    //Route::get('/home', ['as' => '/users', 'uses' => 'Admin\UsersController@index']);
});

//Block for notmal auth
$router->group(['middleware' => ['auth']], function() {
    //Canvas User profile and crop segment
    Route::get('jcrop','Admin\UsersController@jcropview');
    Route::post('/users/jcrop','Admin\UsersController@jcroppost');
    
    //Editor segment
    Route::resource('/canvas','Admin\CanvasController');
    Route::resource('/cover','EcoverController');
    Route::get('/editor/{id}','EcoverController@getSizes');
    
    Route::post('/editor/save','EcoverController@saveCanvas');
    Route::post('/editor/clonesave','EcoverController@cloneCanvas');
    Route::get('/design','EcoverController@getCanvasSizes');
    Route::get('/getCanvasAjax','EcoverController@getCanvasAjax');
    Route::get('/getCategoryAjax','EcoverController@getCategoryAjax');
    Route::get('/home', ['as' => '/editor', 'uses' => 'EcoverController@getSizes']);  
    Route::post('/editor/upload_image/{id}','EcoverController@uploadUserMedia');
    Route::post('/editor/get_user_images/{id}','EcoverController@getUserImages');
    
    //Upload Media and Images segment
    Route::post('/media/uploads','MediaController@uploads');
    Route::post('/media','MediaController@index');
    Route::resource('/media','MediaController');
    Route::post('/media','MediaController@index');
    Route::post('/media/{id}','MediaController@destroy');
    
   
});

 //Export Canvas segment
Route::post('/exports','Admin\CanvasController@exportCanvas');
 

app/PatternImage.php
<?php

namespace editor;

use Illuminate\Database\Eloquent\Model;


class PatternImage extends Model
{
    
    protected $table = 'pattern';
    protected $fillable = ['id', 'media_id', 'color', 'type', 'title', 'price','status'];
    
    public function media() {
        return $this->belongsTo('editor\Media', 'media_id', 'id');
    }
}

app/Http/Controllers/Admin/PatternImageController.php
<?php

namespace editor\Http\Controllers\Admin;

use Illuminate\Http\Request;
use editor\Http\Requests;
//use Illuminate\Support\Facades\Request;
use editor\Http\Requests\CreatePatternImageRequest;
use editor\Http\Controllers\Controller;
use editor\Category;
use editor\Media;
use Intervention\Image\ImageManagerStatic;
//use editor\Mockup;
use editor\Mockup3d;
use editor\Menu;
use editor\Canvas;
use editor\PatternImage;
use editor\User;
use editor\Template;
use Input;
use DB;
use Validator;
use Image;
use Session;
use Auth;

class PatternImageController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public $base_url;
    public function __construct() {
        $this->base_url;
    }

    public function index() {
        $pattern_image = PatternImage::with('media')->paginate(config('app.pagination_limit'));
//          echo"<pre>";
//          print_r($pattern_image);
//          die;
        return view('admin.pattern_image.index', compact('pattern_image'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $pattern_image = DB::table('pattern')->get();
        return view('admin.pattern_image.create', compact('pattern_image'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePatternImageRequest $request) {
        $input = $request->all();
        
         $media = new Media();
        if (isset($input)) {
//            $image = $request->file('media_id');
//            $filename = time().'_'.$image->getClientOriginalName();
//            $path_pro = public_path('uploads/prolix/' . $filename);
//            //Image::make($image->getRealPath())->save($path_pro);
////            $media->file_name = $filename;
////             $media->file_location = 'uploads/prolix/' .time().'_'.$image->getClientOriginalName() ;
//             $media->save();
//             $input['media_id'] = $media->id;
            
            
            $response['status'] = 'success';
            $response['image_path'] = $media->image->url('thumb');
            $response['id'] = $media->id;
            $response['message'] = '<bold><u>'.$media->image_file_name.'</u></bold> has been uploaded successfully';            
        } else {
            $response['status'] = 'error';
            $response['image_path'] = $media->image->url('thumb');
            $response['id'] = $media->id;
            $response['message'] = '<bold>Error while uploading file: '.$media->image_file_name.'</bold>';  
        }
        echo json_encode($response);
        $pattern_image = PatternImage::create($input);
        \Session::flash('message', 'New Pattern OR Image has been Created.!');
        \Session::flash('message-type', 'success');
        return redirect('/pattern');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {

        $pattern_image = PatternImage::with(['media'])->findOrFail($id);
        return view('admin.pattern_image.edit', compact('pattern_image'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $validator = Validator::make($request->all(), ['media_id' => 'required', 'type' => 'required', 'title' => 'required']);
        if ($validator->fails()) {
            return redirect('/pattern/' . $id . '/edit')
                            ->withErrors($validator)
                            ->withInput();
        }
        $input = $request->all();
        $pattern_image = PatternImage::findorFail($id);
        $pattern_image->update($input);
        \Session::flash('message', 'Pattern or Image has been updated !');
        \Session::flash('message-type', 'success');
        return redirect('/pattern');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        PatternImage::destroy($id);
        \Session::flash('message', 'Pattern or Image deleted successfully !');
        \Session::flash('message-type', 'success');
        return redirect('/pattern');
    }

    /**
     * Load all Pattern, Image, Template Data on frontend editor.
     *
     * @return \Illuminate\Http\Response
     */
    public function loadTabdata(Request $request) {
         $tabType = isset($_GET['tog']) ? $_GET['tog'] : 1;
        $offset = isset($_GET['limit']) ? $_GET['limit'] : 10;
        $limit = 9;
        $response = array();
        
        /* tog=2 defines template
         * tog=3 define Text
         * tog=4 define pattern
         * tog=5 define uploads
         * tog=6 define images
         */

        switch ($tabType) {
            case '2':
                
                $width = $_GET['width'];
                $height = $_GET['height'];
                $id = $_GET['id'];
                
                
//                $response = DB::select("SELECT oe_canvas.* , oe_users.id as uid , oe_users.first_name , oe_users.last_name  
//                                        FROM oe_canvas 
//                                        LEFT JOIN oe_users
//                                        ON oe_canvas.user_id=oe_users.id
//                                        WHERE oe_canvas.width='$width' and oe_canvas.height='$height' and oe_canvas.user_id=1 ");
                if(Auth::user()->id == 1){
                    $response = Canvas::with('users')
                            ->where('id', '!=',$id)
                            ->where('width','=',$width)->where('height','=',$height)
                            ->where('status','=', 1)
                            ->get();
                }else{
                    $response = Canvas::with('users')
                        ->whereIn('user_id',[Auth::user()->id,1])
                        ->where('id', '!=',$id)
                        ->where('width','=',$width)->where('height','=',$height)
                        ->where('status','=', 1)
                        ->get();
                }
                
                
                foreach ($response as $key => $value) {
                    $can_frame_id = explode(',', $value->frame_id);
                    $frame_data[$key] = DB::table('frames')->where("id", $can_frame_id[0])->first();
                }
               if(!empty($frame_data)){
                foreach ($frame_data as $key => $value) {
                    $response[$key]->frame_image = $value->frame_image;
                }
               }
//                echo "<pre>";
//                print_r($response);
//                die;
                echo json_encode($response);
                die;
            case '3':
                //currently not using at all. text table also not exist. This is future case if extended
                $response = Template::with('text')->get();
                break;
            case '4':
//                $response = DB::select('SELECT oe_pattern.* , oe_media.*
//                                        FROM oe_pattern LEFT JOIN oe_media
//                                        ON oe_pattern.media_id=oe_media.id  
//                                        where oe_pattern.type="pattern" limit ' . $offset . ',' . $limit);

                $response = PatternImage::with('media')->where('type', '=', 'pattern')->offset($offset)->limit($limit)->get();
                break;
            case '5':
//                $response = Media::orderBy('id', 'desc')->get();
                break;
            case '6':
//                $response = DB::select('SELECT oe_pattern.* , oe_media.* 
//                                        FROM oe_pattern LEFT JOIN oe_media
//                                        ON oe_pattern.media_id=oe_media.id  
//                                        where oe_pattern.type="image" limit ' . $offset . ',' . $limit);
                $response = PatternImage::with('media')->where('type', '=', 'image')->offset($offset)->limit($limit)->get();
                break;
             case '7':
//                $response = DB::select('SELECT oe_pattern.* , oe_media.*
//                                        FROM oe_pattern LEFT JOIN oe_media
//                                        ON oe_pattern.media_id=oe_media.id  
//                                        where oe_pattern.type="pattern" limit ' . $offset . ',' . $limit);

                $response = PatternImage::with('media')->where('type', '=', 'pattern')->offset($offset)->limit($limit)->get();
                break;
            
        }
//        echo "<pre>";print_r($response);die();
        foreach ($response as $i => $details) {
            $response[$i]['original_src'] = url() . $details->media->image->url();
            $response[$i]['thumb_src'] = url()  . $details->media->image->url('thumb');
            $response[$i]['medium_src'] = url()  . $details->media->image->url('medium');
        }
        echo json_encode($response);
        die();
    }

    /**
     * Get Template Data By using template ID
     * @return \Illuminate\Http\Response
     */
    public function getTemplateData() {
        $id = $_POST['tid'];
        $response = DB::table('canvas')->where("id",'=',$id)->first();

        $can_frame_id = explode(',', $response->frame_id);
        if(!empty($can_frame_id)){

resources/views/admin/pattern_image/create.blade.php
@extends ('app')
@section('content')

{!! Form::open(['class' => 'form-horizontal','url'=>'/pattern','files'=>true]) !!}
<div class="panel panel-default">
    <div class="panel-heading">New Background</div>
    <div class="panel-body">
        <div class="form-group">
            <label class="col-lg-2 control-label"> Select Type <span class="xs-astric">*</span></label>
			<span><i class="fa fa-sort-desc create-ican" aria-hidden="true"></i>
</span>
            <select class="image_type create" name="type" style="margin-left: 15px;">
                <option value="">Type </option>
                <option value="pattern" selected="selected">Pattern 
                </option>
                <option value="image">Image
                </option>
            </select>
        </div><!--form control-->
        <div class="form-group">   
            <label class="col-lg-2 control-label"></label>
            <div class="col-lg-10 background-text "></div>
            <div class="col-lg-10 image-text"></div>
            
        </div>
        <div class="color form-group">
            <label class="col-lg-2 control-label">Background Color</label>
            <div class="col-lg-10">
                {!! Form::text('color', '', ['class' => 'form-control color_picker', 'placeholder' => 'Color']) !!}
            </div>
        </div><!--form control-->
        <div class="form-group">
            <label class="col-lg-2 control-label">Title <span class="xs-astric">*</span></label>
            <div class="col-lg-10">
                {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Title']) !!}
            </div>
        </div><!--form control-->
<!--        <div class="form-group">
            <label class="col-lg-2 control-label">Price</label>
            <div class="col-lg-10">
                {!! Form::text('price', null, ['class' => 'form-control', 'placeholder' => 'Price']) !!}
            </div>
        </div>form control-->
        <div class="form-group">
            <label class="col-lg-2 control-label">Select Media <span class="xs-astric">*</span></label>
            <a type="button" class="btn btn-primary gallery" data-toggle="modal" data-target="#myUploads" data-media-id="media_id" data-media-type="radio" data-media-source="pattern" data-media-collect="media_pictures_collect">Gallery</a>
        </div>
        {!! Form::hidden('media_id', null, ['class' => 'form-control', 'placeholder' => 'Media', 'id'=>'media_id']) !!}
        <div class="row media_pictures_collect" id="media_pictures_collect" style="padding: 10px;text-align: right;"></div>
        <div class="pull-right">
            <input type="submit" class="btn btn-success" value="Save" />
        </div>
    </div>
</div>


{!! Form::close() !!}
@stop

resources/views/admin/pattern_image/edit.blade.php
@extends ('app')
@section('page-header')
<h2 align='center'>Edit</h2>
@endsection
@section('content')



{!! Form::model($pattern_image , ['class' => 'form-horizontal', 'role' => 'form', 'action'=>['Admin\PatternImageController@update' , $pattern_image->id] , 'method' => 'PATCH','files' => true]) !!}
<div class="panel panel-default" id="edit-panel-page">
    <div class="panel-heading">Edit Background</div>
    <div class="panel-body">
        <div class="form-group">
            <label class="col-lg-12 control-label">Select Type <span class="xs-astric">*</span></label>
           <div class="col-lg-12">  <select name="type" style="" class="pattern-edit_section">
                <option value="">Select Type</option>
    
                <?php $data = array('pattern' => 'Pattern', 'image' => 'Image') ?>
                @foreach ($data as $k => $val)
                <?php $selected = ( $pattern_image->type == $k ) ? "selected" : "" ?>
                <option value="{{ $k }}" {{$selected}}>{{ $val }}</option>
                @endforeach
            </select></div>
        </div>

        <div class="form-group">
            <label class="col-lg-12 control-label">Color </label>
            <div class="col-lg-10">
                {!! Form::text('color', $pattern_image->color, ['class' => 'form-control color_picker', 'placeholder' => 'Color']) !!}
            </div>
        </div>
        <div class="form-group">
            <label class="col-lg-12 control-label">Title <span class="xs-astric">*</span></label>
            <div class="col-lg-10">
                {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Title']) !!}
            </div>
        </div><!--form control-->
<!--        <div class="form-group">
            <label class="col-lg-2 control-label">Price</label>
            <div class="col-lg-10">
                {!! Form::text('price', null, ['class' => 'form-control', 'placeholder' => 'Price']) !!}
            </div>
        </div>form control-->
    </div><!--form control-->
    <div class="form-group media-form-page">
	 <a type="button" data-flag="edit" class="btn btn-primary gallery" data-toggle="modal" data-target="#myUploads" data-media-id="media_id" data-media-type="radio" data-media-source="pattern" data-media-collect="media_pictures_collect">Gallery</a>
      </div>
	  <div class="form-group media-form-page">
	  <label class="col-lg-12 control-label">Uploaded Media <span class="xs-astric">*</span></label>
       <img height="50" width="40" src="<?php echo url().$pattern_image->media->image->url('thumb'); ?>">
    </div>

    {!! Form::hidden('media_id', null, ['class' => 'form-control', 'placeholder' => 'Media', 'id'=>'media_id']) !!}
    <div class="row media_pictures_collect" id="media_pictures_collect" style="padding: 10px;text-align: right;"></div>

    <div class="pull-right">
        <p>
            <input type="submit" class="btn btn-success" value="Save" />
        </p>
    </div>
</div>
</div>
{!! Form::close() !!}
@stop

resources/views/admin/pattern_image/index.blade.php
@extends ('app')
@section('content')
<div class="tab-content">
    <div role="tabpanel" class="tab-pane active">
        <!-- <div class ="description">
             <div>Add images for the frontend(customization tool), There are two type of image you can save </div>
             <div>-Image : These type of images will be shown in the image tab of the frontend tool.</div>
             <div>-Background: These Images will be shown in the background tab of the frontend tool.</div>
             
         </div>-->
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i>Backgrounds</div>
                <div class="tools">
                    <a href="javascript:;" class="collapse"> </a>
                </div>
            </div>
            <div class="portlet-body flip-scroll">
                <table class="table table-bordered table-striped table-condensed flip-content">
                    <thead class="flip-content">
                        <?php
                       
                        
                        ?>
                        @if($pattern_image && count($pattern_image) >= 1)
                        <tr>
                            <!--<th>ID</th>-->
                            <th>Title</th>
                            <th>Media</th>
                            <th>Background Color</th>
                            <th>Type</th>
<!--                            <th>Price</th>-->
                            <th>Created Date</th>
                            <th>Last Updated</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                        @foreach($pattern_image as $item)

                        <tr>
                             <!--<td>{!! $item->id !!}</td>-->
                            <td>{!! $item->title !!}</td>
                            <td><img src="{!! $item->media->image->url('thumb') !!}"></td>
                            <td>{!! $item->color !!}</td>
                            <td>{!! ucfirst($item->type) !!}</td>
                            <!--<td>{!! $item->price !!}</td>-->
                            <td>{!! $item->created_at->format('d-M, Y  (H:i:s)') !!}</td>
                            <td>{!! $item->updated_at->diffForHumans() !!}</td>
                            <td> 
                                <a class="app-operation-left" href="{!!route('pattern.edit', $item->id)!!}">
                                    <i class="fa fa-pencil" aria-hidden="true"></i>						
                                </a>
                                {!! Form::open(['method' => 'DELETE', 'class'=>'del-css', 'route' => array('pattern.destroy', $item->id),'onsubmit' => 'return ConfirmDelete()']) !!}
                                  <button type="submit" class="submit-btn-cls"> 
                                    <i class="fa fa-trash-o" aria-hidden="true"></i>
                                </button>
                                {!! Form::close() !!} 

                            </td>


                        </tr>

                        @endforeach
                        @else
                    <h3 align='center'>Nothing found!</h3>
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--<div>
    <a class="btn btn-success" href="<?php echo url(); ?>/pattern/create" style="margin-bottom:15px;">+ Add New</a>
</div>-->

<button type="button" data-target="#myModal" data-toggle="modal" data-tooltip="tooltip" class="btn btn-success" style="margin-bottom:15px;">+ Add New</button>

<div class="modal fade background-popup" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only"></span></button>
                <h4 class="modal-title panel-heading" id="myModalLabel">New background</h4>
            </div>
            <div class="modal-body " align="center">
                {!! Form::open(['class' => 'form-horizontal','url'=>'/pattern','files'=>true]) !!}
                <div class="panel panel-default">
                    <div class="panel-body panel-background-header">
                        <div class="form-group select-type">
                            <label class="col-lg-12 control-label" style="padding-left:0px;"> Select Type <span class="xs-astric">*</span></label>
                            <span><i class="fa fa-sort-desc create-ican" aria-hidden="true"></i>
                            </span>
                            <select class="image_type create" name="type" style="margin-left: 15px;">
                                <option value="">Type </option>
                                <option value="pattern" selected="selected">Background 
                                </option>
                                <option value="image">Image
                                </option>
                            </select>
                        </div><!--form control-->
                        <div class="form-group">   
                            <label class="col-lg-12 control-label"></label>
                            <div class="col-lg-12 background-text "></div>
                            <div class="col-lg-12 image-text"></div>
                        </div>
                        <div class="color form-group">
                            <label class="col-lg-12 control-label">Background Color</label>
                            <div class="col-lg-12">
                                {!! Form::text('color', '', ['class' => 'form-control color_picker', 'placeholder' => 'Color']) !!}
                            </div>
                        </div><!--form control-->
                        <div class="form-group">
                            <label class="col-lg-12 control-label">Title <span class="xs-astric">*</span></label>
                            <div class="col-lg-12">
                                {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Title']) !!}
                            </div>
                        </div> 
<div class="form-group pull-left">
                              <div id="mulitplefileuploader2" style="display: none;">Browse ...</div>
                        </div>
						
                        <div class="form-group">
                            <label class="col-lg-12 control-label">Select Media <span class="xs-astric">*</span></label>
                            <div class="col-lg-12 media_pictures_collect" id="media_pictures_collect">                                
                                <!--<form id="upload_content_frm" method="post" action="#">-->
                                <input type="hidden" id="media_source" value="main">
                                <input type="hidden" id="media_limit" value="1">
                                <input type="hidden" id="renderMediaTotal" value="0">
                                <input type="hidden" name="media_id" id="media_id" value="">
                                <div class="row loading-media-container">
                                    <div id="LoadingImage">
                                        <img src="<?php echo url(); ?>/images/ajax-loader.gif" >
                                    </div> 

                                    <fieldset>
                                        <div class="media-inner-box">
                                            <div id="thumbs_store2" class="gallery"></div>
                                        </div>
                                    </fieldset>
                                </div>

                                <div class="load-more" style="text-align:center; padding: 15px;">
                                    <a class="more">Load more</a>
                                </div>

                                <!--div class="row" style="border-top : 1px solid #f1f1f1;text-align: right;padding: 15px;">
                                    <div class="col-lg-12">
                                        <input type="submit" value="Okay" class="btn btn-info">
                                        <button class="btn btn-default" data-dismiss="modal" class="close" type="button">
                                            Cancel
                                        </button>
                                    </div>

                                </div-->
                                <!--</form>-->
                            </div>
                        </div>
                        <!--                        <div class="col-md-3">
                                                    {!! Form::file('media_id', null, ['class' => 'form-control', 'placeholder' => 'Media', 'id'=>'media_id']) !!}
                                                </div>--> 
                        {!! Form::submit('SAVE', array('class' => 'btn btn-success pull-right')) !!}
                        {!! Form::close() !!}

                        {!! Form::open(['class' => 'form-horizontal','url'=>'/media/uploads','files'=>true]) !!}
                        

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="pull-left">
    {!! $pattern_image->total() !!} Pattern(s) total
</div>

<div class="pull-right">
    {!! $pattern_image->render() !!}
</div>
<div class="clearfix"></div>
<script>
    function ConfirmDelete()
    {
        var x = confirm("Are you sure you want to delete this Pattern or Image ?. This will not be recoverable press OK to continue.");
        if (x)
            return true;
        else
            return false;
    }
</script>
@stop