app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Route::get('/', function () {
//     return view('index');
// });
Route::controllers([
   'password' => 'Auth\PasswordController',
]);

Route::get('/', 'Auth\AuthController@getLogin');
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register' , 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

//Block for ACL just use ['auth','roles'] 
//Currently roles section not using anymore
$router->group(['middleware' => ['auth']], function() {
    //Users segment
    Route::resource('/user','UserController');
    Route::resource('/users','Admin\UsersController');

    //Roles segment
    Route::resource('/roles','Admin\RolesController');
    Route::get('/role','Admin\RolesController@roleArea');
    Route::post('/roles/assign','Admin\RolesController@assign');

    //ACL segment
    Route::get('/acl', 'Admin\AclController@update_resources');

    //ACL Permission segment
    Route::get('permissions', 'Admin\AclController@list_permissions');
    Route::get('permissions/{role_id}', 'Admin\AclController@list_permissions');
    Route::post('/permissions','Admin\AclController@add_permission');

    //Category segment
    Route::get('/category/trash','Admin\CategoryController@trashItems');
    Route::get('/category/restore/{c_id}','Admin\CategoryController@restoreItems');
    Route::get('/category/delete/{c_id}','Admin\CategoryController@forceDelete');
    Route::resource('/category','Admin\CategoryController');

    //Mockups
    Route::resource('/mockup3d','Admin\Mockup3dController');
    
    //Template segment
    Route::resource('/template','Admin\TemplateController');
    Route::post('gettemplate','Admin\PatternImageController@getTemplateData');
    Route::get('/edit/{id}','EcoverController@getSizes');

    //Pattrens segment
    Route::get('tabdata','Admin\PatternImageController@loadTabdata');
    Route::resource('/pattern','Admin\PatternImageController');
    Route::get('/showsession','Admin\UsersController@showsession');

    //Route::get('/home', ['as' => '/users', 'uses' => 'Admin\UsersController@index']);
});

//Block for notmal auth
$router->group(['middleware' => ['auth']], function() {
    //Canvas User profile and crop segment
    Route::get('jcrop','Admin\UsersController@jcropview');
    Route::post('/users/jcrop','Admin\UsersController@jcroppost');
    
    //Editor segment
    Route::resource('/canvas','Admin\CanvasController');
    Route::resource('/cover','EcoverController');
    Route::get('/editor/{id}','EcoverController@getSizes');
    
    Route::post('/editor/save','EcoverController@saveCanvas');
    Route::post('/editor/clonesave','EcoverController@cloneCanvas');
    Route::get('/design','EcoverController@getCanvasSizes');
    Route::get('/getCanvasAjax','EcoverController@getCanvasAjax');
    Route::get('/getCategoryAjax','EcoverController@getCategoryAjax');
    Route::get('/home', ['as' => '/editor', 'uses' => 'EcoverController@getSizes']);  
    Route::post('/editor/upload_image/{id}','EcoverController@uploadUserMedia');
    Route::post('/editor/get_user_images/{id}','EcoverController@getUserImages');
    
    //Upload Media and Images segment
    Route::post('/media/uploads','MediaController@uploads');
    Route::post('/media','MediaController@index');
    Route::resource('/media','MediaController');
    Route::post('/media','MediaController@index');
    Route::post('/media/{id}','MediaController@destroy');
    
   
});

 //Export Canvas segment
Route::post('/exports','Admin\CanvasController@exportCanvas');
 

resources/views/includes/content-theme.blade.php
    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                            <h4 class="modal-title">Modal title</h4>
                        </div>
                        <div class="modal-body">
                            Widget settings form goes here
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn blue">Save changes</button>
                            <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!-- /.modal -->
            <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
            <!-- BEGIN STYLE CUSTOMIZER -->
            <div class="theme-panel hidden-xs hidden-sm">
<!--                <div class="toggler">
                </div>-->
                <div class="toggler-close">
                </div>
                <div class="theme-options">
                    <div class="theme-option theme-colors clearfix">
                        <span>
                        THEME COLOR </span>
                        <ul>
                            <li class="color-default current tooltips" data-style="default" data-container="body" data-original-title="Default">
                            </li>
                            <li class="color-darkblue tooltips" data-style="darkblue" data-container="body" data-original-title="Dark Blue">
                            </li>
                            <li class="color-blue tooltips" data-style="blue" data-container="body" data-original-title="Blue">
                            </li>
                            <li class="color-grey tooltips" data-style="grey" data-container="body" data-original-title="Grey">
                            </li>
                            <li class="color-light tooltips" data-style="light" data-container="body" data-original-title="Light">
                            </li>
                            <li class="color-light2 tooltips" data-style="light2" data-container="body" data-html="true" data-original-title="Light 2">
                            </li>
                        </ul>
                    </div>
                    <div class="theme-option">
                        <span>
                        Layout </span>
                        <select class="layout-option form-control input-small">
                            <option value="fluid" selected="selected">Fluid</option>
                            <option value="boxed">Boxed</option>
                        </select>
                    </div>
                    <div class="theme-option">
                        <span>
                        Header </span>
                        <select class="page-header-option form-control input-small">
                            <option value="fixed" selected="selected">Fixed</option>
                            <option value="default">Default</option>
                        </select>
                    </div>
                    <div class="theme-option">
                        <span>
                        Sidebar Mode</span>
                        <select class="sidebar-option form-control input-small">
                            <option value="fixed">Fixed</option>
                            <option value="default" selected="selected">Default</option>
                        </select>
                    </div>
                    <div class="theme-option">
                        <span>
                        Sidebar Menu </span>
                        <select class="sidebar-menu-option form-control input-small">
                            <option value="accordion" selected="selected">Accordion</option>
                            <option value="hover">Hover</option>
                        </select>
                    </div>
                    <div class="theme-option">
                        <span>
                        Sidebar Style </span>
                        <select class="sidebar-style-option form-control input-small">
                            <option value="default" selected="selected">Default</option>
                            <option value="light">Light</option>
                        </select>
                    </div>
                    <div class="theme-option">
                        <span>
                        Sidebar Position </span>
                        <select class="sidebar-pos-option form-control input-small">
                            <option value="left" selected="selected">Left</option>
                            <option value="right">Right</option>
                        </select>
                    </div>
                    <div class="theme-option">
                        <span>
                        Footer </span>
                        <select class="page-footer-option form-control input-small">
                            <option value="fixed">Fixed</option>
                            <option value="default" selected="selected">Default</option>
                        </select>
                    </div>
                </div>
            </div>
            <!-- END STYLE CUSTOMIZER -->
            <!-- BEGIN PAGE HEADER-->
<!--            <h3 class="page-title">
                Blank Page
            </h3>-->
<!--            <div class="page-bar">
                <ul class="page-breadcrumb">
                    <li>
                        <i class="fa fa-home"></i>
                        <a href="index.html">Home</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">Page Layouts</a>
                        <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                        <a href="#">Blank Page</a>
                    </li>
                </ul>
                <div class="page-toolbar">
                    <div class="btn-group pull-right">
                        <button type="button" class="btn btn-fit-height grey-salt dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true">
                        Actions <i class="fa fa-angle-down"></i>
                        </button>
                        <ul class="dropdown-menu pull-right" role="menu">
                            <li>
                                <a href="#">Action</a>
                            </li>
                            <li>
                                <a href="#">Another action</a>
                            </li>
                            <li>
                                <a href="#">Something else here</a>
                            </li>
                            <li class="divider">
                            </li>
                            <li>
                                <a href="#">Separated link</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>-->
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <div class="row">
                <div class="col-md-12">
                    @include('includes.partials.messages')
                   @if($errors->any())
                    <div class="row">
                        <ul class='alert alert-danger col-lg-12'>
                            @foreach($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                    @yield('content')
                </div>
            </div>
            <!-- END PAGE CONTENT-->
        </div>
    </div>
    <!-- END CONTENT -->

resources/views/includes/footer-blank.blade.php
<div class="copyright"> <?php echo date('Y'); ?> @BannersPro. Admin Dashboard Template. </div>

<script src="<?php echo url(); ?>/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/jquery-validation/js/jquery.validate.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/scripts/app.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/pages/scripts/login.min.js" type="text/javascript"></script>
</body>
</html>

resources/views/includes/footer-theme.blade.php
<!-- BEGIN FOOTER -->
<div class="page-footer">
    <div class="page-footer-inner">
        <?php echo date("Y"); ?> &copy; BannersPro.
    </div>
    <div class="page-footer-tools">
        <span class="go-top">
            <i class="fa fa-angle-up"></i>
        </span>
    </div>
</div>
<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="../assets/global/plugins/respond.min.js"></script>
<script src="../assets/global/plugins/excanvas.min.js"></script> 
<![endif]-->

<script src="<?php echo url(); ?>/assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/js/bootstrap-toggle.min.js"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>

<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->







<script src="<?php echo url(); ?>/assets/global/plugins/flot/jquery.flot.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/flot/jquery.flot.resize.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/flot/jquery.flot.categories.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/jquery.pulsate.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/bootstrap-daterangepicker/moment.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>
<!-- IMPORTANT! fullcalendar depends on jquery-ui-1.10.3.custom.min.js for drag & drop support -->
<script src="<?php echo url(); ?>/assets/global/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/global/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/plugins/js/jquery.gritter.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?php echo url(); ?>/plugins/js/app.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/layouts/layout/scripts/layout.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/assets/layouts/global/scripts/quick-sidebar.min.js" type="text/javascript"></script>


<script src="<?php echo url(); ?>/plugins/js/tasks.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/plugins/js/jquery.Jcrop.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/fileupload/jquery.uploadfile.min.js" type="text/javascript"></script>
<script src="<?php echo url(); ?>/js/jquery.minicolors.min.js" type="text/javascript"></script>
<!--    <script src="<?php //echo url();       ?>/js/jquery.form.js" type="text/javascript"></script>-->
<script src="<?php echo url(); ?>/js/adminscript.js" type="text/javascript"></script>

</body>
</html>

resources/views/includes/header-blank.blade.php
<!DOCTYPE html>
<!--
@description: This header will be used only for the login,registration, forget password page. Not using for innter pages
-->
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->

    <head>
        <meta charset="utf-8" />
        <meta name="_token" content="{{ csrf_token() }}" />
        <title>BannersPro | User Login 1</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="" name="description" />
        <meta content="" name="author" />
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="//fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
        <link href="<?php echo url(); ?>/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo url(); ?>/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo url(); ?>/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo url(); ?>/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo url(); ?>/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo url(); ?>/assets/global/plugins/select2/css/select2.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo url(); ?>/assets/global/plugins/select2/css/select2-bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="<?php echo url(); ?>/assets/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
        <link href="<?php echo url(); ?>/assets/pages/css/login.min.css" rel="stylesheet" type="text/css" />
        <link rel="shortcut icon" href="favicon.ico" /> </head>
    <body class=" login">

resources/views/includes/header-theme.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="_token" content="{!! csrf_token() !!}" />
        <title>Online Editors</title>

        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('assets/global/plugins/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('assets/global/plugins/simple-line-icons/simple-line-icons.min.css')}}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('assets/global/plugins/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('assets/global/plugins/uniform/css/uniform.default.css')}}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css')}}" rel="stylesheet" type="text/css"/>

        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN PAGE LEVEL PLUGIN STYLES -->
        <link href="{{ asset('plugins/jquery.gritter.css')}}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('assets/global/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css')}}" rel="stylesheet" type="text/css"/>


        <!-- END PAGE LEVEL PLUGIN STYLES -->
        <!-- BEGIN PAGE STYLES -->
        <link href="{{ asset('plugins/tasks.css')}}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css')}}" rel="stylesheet" type="text/css" />

        <link href="{{ asset('assets/global/css/components.min.css')}}" rel="stylesheet" id="style_components" type="text/css" />
        <link href="{{ asset('assets/global/css/plugins.min.css')}}" rel="stylesheet" type="text/css" />

        <link href="{{ asset('assets/pages/css/profile.min.css')}}" rel="stylesheet" type="text/css" />


        <!-- END PAGE STYLES -->
        <!-- BEGIN THEME STYLES -->
        <link href="{{ asset('assets/global/css/components.css')}}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('assets/global/css/plugins.css')}}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('assets/layouts/layout/css/layout.css')}}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('assets/layouts/layout/css/themes/default.css')}}" rel="stylesheet" type="text/css" id="style_color"/>
        <link href="{{ asset('assets/layouts/layout/css/custom.css')}}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('fileupload/uploadfile.css')}}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('css/jquery.minicolors.css')}}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('css/admincss.css')}}" rel="stylesheet" type="text/css"/>
        <link href="{{asset('plugins/jcrop.css')}}" rel="stylesheet" type="text/css"/>
        <!-- END THEME STYLES -->

        <link href="{{ asset('css/bootstrap-toggle.min.css')}}" rel="stylesheet">
        <link href="{{ asset('css/uimcss.css')}}" rel="stylesheet">

        <link rel="shortcut icon" href="favicon.ico"/>
        <script src="{{ asset('assets/global/plugins/jquery.min.js')}}" type="text/javascript"></script>
       

        <script> $baseUrl = '<?php echo url(); ?>';</script>
    </head>

    <body ng-app="editorApp">
        <!-- BEGIN HEADER -->
        <div class="page-header navbar navbar-fixed-top">
            <!-- BEGIN HEADER INNER -->
            <div class="page-header-inner">
                <!-- BEGIN LOGO -->
                <div class="page-logo">
                    <a href="<?php echo url(); ?>/users">
                        <img src="{{ asset('assets/layouts/layout/img/banner-logo.jpg')}}" alt="logo" class="logo-default"/>
                    </a>
                    <div class="menu-toggler sidebar-toggler hide"></div>
                </div>
                <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"></a>
                
                <!-- BEGIN TOP NAVIGATION MENU -->
                <div class="top-menu">
                    <ul class="nav navbar-nav pull-right">
                        <li class="dropdown dropdown-user">
                            <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                @if(Auth::user()->profile_pic !='')
                                {!! Html::image('users_images/'.Auth::user()->profile_pic, 'image', array(  'height' => 80 ))  !!}
                                @else
                                {!! Html::image('images/avatar.png', 'image') !!}
                                @endif
                                <span class="username">
                                    {{  ucfirst(Auth::user()->first_name) }} </span>
                                <i class="fa fa-angle-down"></i>
                            </a>-->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                <span class="username">{{  ucfirst(Auth::user()->first_name)}} </span>
                                <span class="username-icon"><i class="fa fa-user"></i></span>
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="<?php echo url() . '/users/' . (Auth::user()->id) . '/edit'; ?>"><i class="icon-user"></i> View Profile</a>
                                </li>
                                <li>
                                    <a href="<?php echo url() . '/auth/logout'; ?>"><i class="icon-lock"></i> Logout</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- END TOP NAVIGATION MENU -->
            </div>
        </div>
        <!-- END HEADER -->

resources/views/includes/nav.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="">Online Editor</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>{!! link_to('/', 'Home') !!}</li>
                <li>{!! link_to('/editor', 'Online Editor') !!}</li>
                @if(!Auth::guest() && Auth::user()->role_id!='1')
                @endif
                @if(!Auth::guest() && Auth::user()->role_id=='1')

                <li>{!! link_to('users', 'Dashboard') !!}</li>
                <li>{!! link_to('/role', 'Role Area') !!}</li>
                <li>{!! link_to('permissions', 'Permission Area') !!}</li>
                <li>{!! link_to('/category', 'Category Area') !!}</li>
                <!--<li>{!! link_to('roles', 'Assign Role') !!}</li>-->
                <li>{!! link_to('acl', 'Update New Resources') !!}</li>
              

                @endif
            </ul>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    @if (Auth::guest())

                    <li>{!! link_to('auth/login', 'Login') !!}</li>
                    <li>{!! link_to('auth/register', 'Register') !!}</li>

                    @else
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Hello, {{  ucfirst(Auth::user()->first_name) }} <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>{!! link_to_route('user.show', "View Profile", Auth::user()->id) !!}</li>
                             @if(!Auth::guest() && Auth::user()->role_id!='2')
                            @endif
                            <li>{!! link_to('auth/logout', 'Logout') !!}</li>
                        </ul>
                    </li>
                    @endif
                </ul>
            </div>
        </div>
        </div>
</nav>